In [3]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("test.csv",sep=";")

In [3]:
df.head(10)

,sensor_id,sensor_type,location,lat,lon,timestamp,value_type,value
0,162,pms5003,73,-1.421,36.953,2020-01-25T03:55:08.849233+00:00,P2,6.6
1,162,pms5003,73,-1.421,36.953,2020-01-25T03:55:08.849233+00:00,P1,7.8
2,162,pms5003,73,-1.421,36.953,2020-01-25T03:55:08.849233+00:00,P0,3.0
3,162,pms5003,73,-1.421,36.953,2020-01-28T13:09:58.333636+00:00,P2,4.0
4,162,pms5003,73,-1.421,36.953,2020-01-28T13:09:58.333636+00:00,P1,7.0
5,162,pms5003,73,-1.421,36.953,2020-01-28T13:09:58.333636+00:00,P0,2.2
6,162,pms5003,73,-1.421,36.953,2020-01-30T03:39:44.568737+00:00,P2,25.8
7,162,pms5003,73,-1.421,36.953,2020-01-30T03:39:44.568737+00:00,P1,29.6
8,162,pms5003,73,-1.421,36.953,2020-01-30T03:39:44.568737+00:00,P0,15.2

In [5]:
def wrangle(csv_path):
    df = pd.read_csv(csv_path,sep=";",low_memory=False)
    

    values = ['P2','P1', 'P1','temperature','humidity','height']
    df = df[df.value_type.isin(values) == True]
    

    df['value']=df.value.str.replace('[^\d.]', '',regex=True).astype(float)
    
    df['P2'] = np.where(df['value_type'] == "P2", df["value"], 'NaN')
    df['P1'] = np.where(df['value_type'] == "P1", df["value"], 'NaN')
    df['P0'] = np.where(df['value_type'] == "P0", df["value"], 'NaN')
    df['temperature'] = np.where(df['value_type'] == "temperature", df["value"], 'NaN')
    df['humidity'] = np.where(df['value_type'] == "humidity", df["value"], 'NaN')
    df['height'] = np.where(df['value_type'] == 'height', df["value"], 'NaN')
    
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    
    convert_dict = {'value': float,'P2': float,'P1':float,'P0':float,'temperature':float,'humidity':float,'height':float}
    df = df.astype(convert_dict)
    
    df = df.drop(columns=['value'], axis=1)
    
    df = df.rename(columns={"sensor_id": "metadata.sensor_id",
                            "sensor_type": "metadata.sensor_type",
                            "location":"metadata.location",
                            "lat":"metadata.lat",
                            "lon":"metadata.lon",
                            "value_type":"metadata.measrment"})
    return df

In [6]:
frame = wrangle(r"E:\WorldQuant\project_3\data\november_2019_sensor_data_archive.csv")

In [7]:
frame.head()

,metadata.sensor_id,metadata.sensor_type,metadata.location,metadata.lat,metadata.lon,timestamp,metadata.measrment,P2,P1,P0,temperature,humidity,height
0,150,pms5003,7,-1.298,36.791,2019-11-01 00:00:00.139304+00:00,P2,8.000000,NaN,NaN,NaN,NaN,NaN
1,150,pms5003,7,-1.298,36.791,2019-11-01 00:00:00.139304+00:00,P1,NaN,8.000000,NaN,NaN,NaN,NaN
3,103,SDS011,37,-1.316,36.870,2019-11-01 00:00:02.669080+00:00,P2,7.171595,NaN,NaN,NaN,NaN,NaN
4,103,SDS011,37,-1.316,36.870,2019-11-01 00:00:02.669080+00:00,P1,NaN,10.497994,NaN,NaN,NaN,NaN
5,104,DHT22,37,-1.316,36.870,2019-11-01 00:00:02.842468+00:00,temperature,NaN,NaN,NaN,24.699402,NaN,NaN

In [27]:
frame["metadata.measrment"].unique()

array(['P2', 'P1', 'P0', 'temperature', 'humidity', 'height'],
      dtype=object)

In [28]:
frame.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2458917 entries, 0 to 2467826
Data columns (total 13 columns):
 #   Column                Dtype
---  ------                -----
 0   metadata.sensor_id    int64
 1   metadata.sensor_type  object
 2   metadata.location     int64
 3   metadata.lat          float64
 4   metadata.lon          float64
 5   timestamp             datetime64[ns, UTC]
 6   metadata.measrment    object
 7   P2                    float64
 8   P1                    float64
 9   P0                    float64
 10  temperature           float64
 11  humidity              float64
 12  height                float64
dtypes: datetime64[ns, UTC](1), float64(8), int64(2), object(2)
memory usage: 262.6+ MB

In [29]:
frame.to_csv(r"E:\WorldQuant\project_3\data\november_2019_sensor_data_archive_modefied.csv", index=False)